baseURL = 'https://livebug.github.io'
languageCode = 'en-us'
title = "livebug's blog space"
theme = 'nostyleplease'

[author]
  name = "livebug"
  homepage = "livebug.github.io"

[params]
  description = "一个数据搬运工的各种浅尝辄止"
  
  [params.theme_config]
    show_description = true