baseURL = 'https://livebug.github.io'
languageCode = 'en-us'
title = "livebug's blog space"
theme = 'nostyleplease'

[author]
  name = "livebug"
  homepage = "livebug.github.io"

[params]
  description = "Good judgement comes from experience, and experience comes from bad judgement. —— Fred Brooks"
  favicon = "favicon.ico"
  [params.theme_config]
    show_description = true