baseURL = 'https://livebug.github.io'
languageCode = 'en-us'
title = "livebug's blog space"
theme = 'nostyleplease'

[author]
  name = "livebug"
  homepage = "https://livebug.github.io"

[params]
  description = "Good judgement comes from experience, and experience comes from bad judgement. —— Fred Brooks"
  favicon = "favicon.ico"
  [params.theme_config]
    show_description = true
    appearance = "light"
    back_home_text = ".. back to home"
    date_format = "2006-01-02"


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'github'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
 