[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  enableGitalk = true
  [params.theme_config]
    appearance = "light"
    back_home_text = ".."
    date_format = "2006-01-02"
  [params.gitalk] 
    clientID = "611a6636d92469d23028" # 您刚才创建Github Application 的 Client ID
    clientSecret = "e33f7c182796cd46d35977af0c04dcf1cb16b49f" # 您刚才创建Github Application 的 Client Secret
    repo = "livebug.github.io" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "livebug" # 您的GitHub ID
    admin= "livebug" # 您的GitHub ID
    id= "location.pathname" # 文章页面的链接地址就是ID
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
